### ISSUE TITLE
"All CUDA-capable devices are busy or unavailable" when running on Google Colab

### ISSUE THREAD

**Issue by turlando** [yhlleo/DeepSegmentor#26]
Hello,

I'm trying to run your code using the provided [Google Colab notebook](https://colab.research.google.com/drive/13qSMnU1ERU7riHMMiv9MEEr7VTMhfZs9?usp=sharing) but upon issuing the command `sudo sh scripts/test_deepcrack.sh 0;` I get the following error:

```
----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: ./checkpoints                 
                crop_size: 256                           
                 dataroot: ./datasets/DeepCrack            [default: None]
             dataset_mode: deepcrack                     
                direction: AtoB                          
            display_sides: 1                             
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: xavier                        
                 input_nc: 3                             
                  isTrain: False                           [default: None]
             lambda_fused: 1.0                           
              lambda_side: 1.0                           
              load_height: 0                             
                load_iter: 0                               [default: 0]
                load_size: 256                           
               load_width: 0                             
                loss_mode: focal                         
         max_dataset_size: inf                           
                    model: deepcrack                       [default: test]
               n_layers_D: 3                             
                     name: deepcrack                       [default: experiment_name]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_9blocks                
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: 1                             
                     norm: batch                           [default: instance]
                    ntest: inf                           
              num_classes: 1                               [default: 2]
                 num_test: 10000                           [default: 50]
              num_threads: 2                             
                output_nc: 3                             
                    phase: test                          
               preprocess: resize_and_crop               
              results_dir: ./results/                    
           serial_batches: False                         
                   suffix:                               
              use_augment: False                         
                 use_selu: 1                             
                  verbose: False                         
----------------- End -------------------
dataset [DeepCrackDataset] was created
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = create_model(opt)      # create a model given opt.model and other options
  File "/content/DeepSegmentor/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/content/DeepSegmentor/models/deepcrack_model.py", line 45, in init
    self.gpu_ids)
  File "/content/DeepSegmentor/models/deepcrack_networks.py", line 90, in define_deepcrack
    return init_net(net, init_type, init_gain, gpu_ids)
  File "/content/DeepSegmentor/models/networks.py", line 106, in init_net
    net.to(gpu_ids[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 899, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 570, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 593, in _apply
    param_applied = fn(param)
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 897, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Do you have any idea on what is going on? I also tried restarting the Colab instance and verifying the GPU status with `nvidia-smi` but everything looks fine (output below).

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    30W / 149W |      0MiB / 11441MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Let me know if there is any additional information I can provide to help solving the issue.

Thank you for your time and have a nice day.

**Comment by yhlleo** [comment]
Hi @turlando , sorry for the late reply. Did you solve this problem? It seems a problem about the cuda environment.

**Comment by turlando** [comment]
Hi @yhlleo,

unfortunately I wasn't able to solve this issue.

I just have to point out that I'm assisting a friend of mine to run your software and she has no Linux machine at her disposal.

Since I got no luck with Google Colab, I tried to make DeepSegmentor run on her Windows machine. It relies on pytorch >= 0.4.0 and pypi has Windows-compatible wheels for pytorch since version 1.7.0 only. I tried to use 1.7.0, 1.7.1 and other newer versions, but I get some AttributeError (`'torch._C' has no attribute '_cuda_setDevice'` if I'm not mistaken, it's been a while ago and I didn't keep any log). I suspect that it is an API that got removed somewhere around version 1.0.0 but I didn't have the time to dig into your code to patch it to use a more recent pytorch version.

I will try later today to use Google Colab again using the notebook you provided but if in the meanwhile you could try to reproduce the issue on Colab that would really be extremely helpful.

Thank you in advance and have a nice day.

**Comment by turlando** [comment]
I tried again on Google Colab and the error changed in

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    model.test()           # run inference
  File "/content/DeepSegmentor/models/base_model.py", line 105, in test
    self.forward()
  File "/content/DeepSegmentor/models/deepcrack_model.py", line 76, in forward
    self.outputs = self.netG(self.image)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/DeepSegmentor/models/deepcrack_networks.py", line 58, in forward
    conv1 = self.conv1(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 2283, in batch_norm
    input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
```

>RuntimeError: CUDA out of memory. Tried to allocate 6.81 GiB (GPU 0; 14.76 GiB total capacity; 7.40 GiB already allocated; 6.05 GiB free; 7.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

So, sure enough, it is a problem related to the Colab's free plan and/or to resources allocation policies I'm not aware of.

Could you provide any information regarding GPU memory requirements so that I can understand if it's viable to try making it run on the hardware I have at my disposal?

Thank you again.

**Comment by swafe** [comment]
Hello,
I receive the same Error in Colab:

"RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable"

**Comment by swafe** [comment]
Hello,
I think the Error is in the 'test_deepcrack.sh'. Change GPU_IDS=$1 to GPU_IDS='-1' should enable the CPU calculation.

**Comment by yhlleo** [comment]
Hi @turlando , I closed this issue. If you still have the problem after trying, I can open this issue again.
