### ISSUE TITLE
ValueError: signal number 32 out of range

### ISSUE THREAD

**Issue by loyevei** [yhlleo/DeepSegmentor#34]
Thank you for using your task.

But I have a question about testing the DeepCrack.sh
Training the DeepCrack file is good, but I've faced the issue about python 3.5.5 maybe.

---------- Networks initialized -------------
[Network G] Total number of parameters : 14.720 M
-----------------------------------------------
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/deepsegmentor3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/deepsegmentor3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/deepsegmentor3/lib/python3.5/multiprocessing/resource_sharer.py", line 139, in _serve
    signal.pthread_sigmask(signal.SIG_BLOCK, range(1, signal.NSIG))
  File "/opt/anaconda3/envs/deepsegmentor3/lib/python3.5/signal.py", line 60, in pthread_sigmask
    sigs_set = _signal.pthread_sigmask(how, mask)
ValueError: signal number 32 out of range

---------------------------------------------------------

Upper one is that I faced the issue.
Already I fixed the num_workers=0 but test_deepcrack.sh wasn't working.
What can I do for that issue?
Please check that issue, Thanks for your favor.

**Comment by GoroYeh-HRI** [comment]
Hi @yhlleo ,
I also got this error when trying to run:
sh ./scripts/train_roadnet.sh 0

Could you please take a look and advise me how to solve this issue? Thank you.

![image](https://github.com/yhlleo/DeepSegmentor/assets/137837175/0607cc4f-0d17-4429-917d-c4580bea629b)

**Comment by yhlleo** [comment]
@loyevei  Do you solve this problem?
